strategy_name: 'adapted_mean' # 'adapted_mean'

# data settings
stock_name: 'EUNL.DE' # search for indicators at https://finance.yahoo.com/
start_date: '2022-02-13' # format yyyy-mm-dd
end_date: '2022-09-20' # format yyyy-mm-dd
frequency: '1d' # 1d (daily) or 1m (minutely), minute data only available for 7 days
window_len: 3 # window length in hours or days for sliding window calculation (depends on frequency value)
spread: 0.1 # assumed spread during trade in [%]

# algorithm settings

# Only for strategy_name: 'adapted_mean'
average_type: 'moving_mean' # 'moving_mean', 'absolut_mean'
band_percentage: 0.3 # [%] percentage band of mean strategy